### ISSUE TITLE
Document this better

### ISSUE THREAD

**Issue by CollinChaffin** [jmichas/PlexTrainingVideoScannerAndAgent#9]
Appreciate any free effort like this however it gets frustrating when things are hard-coded (always a no-no in coding) and not even documented.

For instance, if in the GUI a user turns the debug logging on for this scanner - it will sit and generate thousands of errors unless they too are a DEV and know how to dig through the python code to find this (line #16):
````
loggingPath = 'P:\AppData\Plex Media Server\Logs' #os.path.expandvars(LOC_WIN)
````
and change it since NOBODY except you has a P:\Appdata folder.   That is critical step 1 because out of the box as of today (05-10-2018), this scanner code is not working properly so 100% of users need to first turn on the logging just to confirm that it is failing and why.

**Comment by CollinChaffin** [comment]
So a quick update....the reason this scanner does absolutely NOTHING except error out of the box right now for everyone is in fact the aforementioned hard-coded bad logging path.  However, once you alter line 16 to a valid path then Python will not halt the scanning and it will actually function.

**Comment by abesherman** [comment]
Will this work for Linux as well or is that in line 14?

**Comment by stevenb9** [comment]
The scanner is indeed not working out of the box on mac, changed this line and everything is running fine now

at line 16:
> loggingPath = os.path.expandvars(LOC_MAC)
